import { useEffect } from 'react';
import { Link } from 'wouter';
import {
  Shield, AudioLines, Video, Camera, Mic, ArrowRight,
  ChevronRight, Zap, Lock, Globe2, FileText, Monitor,
  CheckCircle2, Database, FlaskConical, UserCheck, Code2
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useLang } from '@/contexts/LanguageContext';
import { getLoginUrl } from '@/const';
import { useAuth } from '@/_core/hooks/useAuth';

export default function Home() {
  const { t } = useLang();
  const { isAuthenticated } = useAuth();

  useEffect(() => {
    document.title = 'DeepGuard - AI Deepfake Detection & Anti-Scam Platform';
  }, []);

  // Four primary detection modes
  const detectionModes = [
    {
      icon: FileText,
      title: 'Text Detection',
      desc: 'Detect AI-written articles, essays, and messages. Sentence-level probability highlighting.',
      href: '/detect/text',
      color: 'text-emerald-400',
      bg: 'bg-emerald-400/10',
      border: 'hover:border-emerald-400/40',
      badge: 'GPT · BERT · LLaMA',
    },
    {
      icon: Camera,
      title: 'Image Detection',
      desc: 'Identify Midjourney, DALL·E, Stable Diffusion images. Heatmap shows AI-generated regions.',
      href: '/detect/video',
      color: 'text-violet-400',
      bg: 'bg-violet-400/10',
      border: 'hover:border-violet-400/40',
      badge: 'Midjourney · DALL·E · SD',
    },
    {
      icon: Video,
      title: 'Video Detection',
      desc: 'Frame-by-frame deepfake analysis with AI probability timeline. Detect FaceSwap & DeepFaceLab.',
      href: '/detect/video',
      color: 'text-blue-400',
      bg: 'bg-blue-400/10',
      border: 'hover:border-blue-400/40',
      badge: 'FaceSwap · DeepFaceLab',
    },
    {
      icon: AudioLines,
      title: 'Audio Detection',
      desc: 'Detect AI voice cloning, speech synthesis, and deepfake audio. Multi-model cross-validation.',
      href: '/detect/audio',
      color: 'text-cyan-400',
      bg: 'bg-cyan-400/10',
      border: 'hover:border-cyan-400/40',
      badge: 'ElevenLabs · Whisper · TTS',
    },
  ];

  // Multi-model detectors
  const detectors = [
    { name: 'GPT/LLM Detector', desc: 'Identifies text generated by ChatGPT, Claude, Gemini and similar models', accuracy: '94%', color: 'text-emerald-400' },
    { name: 'Diffusion Detector', desc: 'Detects images from Stable Diffusion, Midjourney, DALL·E and other diffusion models', accuracy: '91%', color: 'text-violet-400' },
    { name: 'Deepfake Detector', desc: 'Identifies face-swapped video and audio using FaceSwap, DeepFaceLab engines', accuracy: '89%', color: 'text-blue-400' },
    { name: 'Watermark Detector', desc: 'Scans for SynthID, OpenAI watermarks and metadata left by AI generation tools', accuracy: '96%', color: 'text-cyan-400' },
  ];

  // Trust stats
  const stats = [
    { value: '2M+', label: 'Training samples', sub: 'LAION · FaceForensics++ · DFDC' },
    { value: '94%', label: 'Detection accuracy', sub: 'Verified on benchmark datasets' },
    { value: '2.1%', label: 'False positive rate', sub: 'Industry-leading precision' },
    { value: '<5s', label: 'Analysis speed', sub: 'Real-time protection' },
  ];

  // Use cases
  const useCases = [
    { icon: UserCheck, title: 'Identity Verification', desc: 'Dating apps, remote interviews, KYC — confirm you\'re talking to a real person', href: '/verify' },
    { icon: Shield, title: 'Anti-Scam Protection', desc: 'Detect deepfake video calls, AI voice impersonation, and fraud attempts in real time', href: '/detect/screen' },
    { icon: Code2, title: 'Enterprise API', desc: 'Batch detection for social platforms, news media, and recruitment systems', href: '/api-docs' },
    { icon: Monitor, title: 'Screen Share Monitor', desc: 'Monitor your screen during Zoom, Teams, or any video call for live deepfake detection', href: '/detect/screen' },
  ];

  return (
    <div className="min-h-screen">
      {/* ── Hero ── */}
      <section className="relative min-h-screen flex items-center overflow-hidden grid-bg">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[700px] h-[700px] bg-primary/8 rounded-full blur-[140px]" />
          <div className="absolute top-1/3 left-1/4 w-[300px] h-[300px] bg-violet-500/6 rounded-full blur-[80px]" />
          <div className="absolute bottom-1/4 right-1/4 w-[250px] h-[250px] bg-cyan-500/5 rounded-full blur-[60px]" />
        </div>

        <div className="container relative z-10 pt-24 pb-16">
          <div className="max-w-4xl mx-auto text-center">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-primary/30 bg-primary/10 text-primary text-sm font-medium mb-8">
              <Shield className="w-3.5 h-3.5" />
              <span>Multi-Model AI Content Detection Platform</span>
            </div>

            <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold leading-tight mb-6" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
              <span className="text-foreground">Detect if images, videos,</span>
              <br />
              <span className="text-primary">audio or text are AI generated</span>
            </h1>

            <p className="text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto mb-10 leading-relaxed">
              Four specialized AI detectors running in parallel — text, image, video, and audio.
              Get an AI probability score, confidence level, and detailed source attribution in seconds.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link href="/detect/text">
                <Button size="lg" className="bg-primary text-primary-foreground hover:bg-primary/90 glow-cyan gap-2 px-8 text-base">
                  Start Detecting Free
                  <ChevronRight className="w-4 h-4" />
                </Button>
              </Link>
              {!isAuthenticated && (
                <a href={getLoginUrl()}>
                  <Button size="lg" variant="outline" className="border-border hover:border-primary/50 text-foreground gap-2 px-8 text-base">
                    Sign In
                  </Button>
                </a>
              )}
            </div>

            {/* Trust stats row */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-6 mt-16 max-w-2xl mx-auto">
              {stats.map((s, i) => (
                <div key={i} className="text-center">
                  <div className="text-2xl sm:text-3xl font-bold text-primary mb-0.5" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>{s.value}</div>
                  <div className="text-xs font-medium text-foreground mb-0.5">{s.label}</div>
                  <div className="text-[10px] text-muted-foreground">{s.sub}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-background to-transparent" />
      </section>

      {/* ── Four Detection Modes ── */}
      <section id="features" className="py-24 relative">
        <div className="container">
          <div className="text-center mb-14">
            <h2 className="text-3xl sm:text-4xl font-bold mb-4" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
              Detect Any AI-Generated Content
            </h2>
            <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
              Upload a file or paste text — our system runs multiple detection models simultaneously and cross-validates the results.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 max-w-4xl mx-auto">
            {detectionModes.map((m, i) => (
              <Link key={i} href={m.href}>
                <div className={`group relative p-6 rounded-xl border border-border/60 bg-card ${m.border} transition-all duration-300 hover:bg-card/80 cursor-pointer h-full`}>
                  <div className="flex items-start gap-4">
                    <div className={`w-12 h-12 rounded-xl ${m.bg} flex items-center justify-center flex-shrink-0`}>
                      <m.icon className={`w-6 h-6 ${m.color}`} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <h3 className="font-semibold text-foreground">{m.title}</h3>
                      </div>
                      <p className="text-sm text-muted-foreground leading-relaxed mb-3">{m.desc}</p>
                      <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-muted/50 border border-border/50">
                        <span className={`text-[10px] font-medium ${m.color}`}>{m.badge}</span>
                      </div>
                    </div>
                  </div>
                  <div className={`flex items-center gap-1 mt-4 text-sm ${m.color} opacity-0 group-hover:opacity-100 transition-opacity`}>
                    <span>Start detection</span>
                    <ArrowRight className="w-3.5 h-3.5" />
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* ── Multi-Model Architecture ── */}
      <section className="py-24 bg-card/30 border-y border-border/40">
        <div className="container">
          <div className="text-center mb-14">
            <h2 className="text-3xl sm:text-4xl font-bold mb-4" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
              Four Detectors. One Verdict.
            </h2>
            <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
              We don't rely on a single model. Four specialized detectors run in parallel and their results are cross-validated to produce a final AI probability score and confidence level.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 max-w-5xl mx-auto mb-12">
            {detectors.map((d, i) => (
              <div key={i} className="p-5 rounded-xl border border-border/60 bg-card">
                <div className="flex items-center justify-between mb-3">
                  <FlaskConical className={`w-5 h-5 ${d.color}`} />
                  <span className={`text-sm font-bold ${d.color}`}>{d.accuracy}</span>
                </div>
                <h4 className="font-semibold text-foreground text-sm mb-2">{d.name}</h4>
                <p className="text-xs text-muted-foreground leading-relaxed">{d.desc}</p>
              </div>
            ))}
          </div>

          {/* Output example */}
          <div className="max-w-lg mx-auto p-5 rounded-xl border border-primary/20 bg-primary/5">
            <p className="text-xs text-muted-foreground mb-3 font-medium uppercase tracking-wider">Combined Output Example</p>
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-sm text-foreground">AI Generated Probability</span>
                <span className="text-sm font-bold text-rose-400">87%</span>
              </div>
              <div className="w-full h-2 rounded-full bg-muted overflow-hidden">
                <div className="h-full w-[87%] rounded-full bg-gradient-to-r from-amber-400 to-rose-500" />
              </div>
              <div className="flex items-center justify-between mt-3">
                <span className="text-sm text-foreground">Confidence Score</span>
                <span className="text-sm font-bold text-primary">High (94%)</span>
              </div>
              <div className="mt-3 pt-3 border-t border-border/40">
                <p className="text-xs text-muted-foreground mb-2">Possible Source Models</p>
                <div className="flex flex-wrap gap-1.5">
                  {['Midjourney v6', 'Stable Diffusion XL', 'DALL·E 3'].map(m => (
                    <span key={m} className="px-2 py-0.5 rounded-full bg-muted text-xs text-foreground border border-border/50">{m}</span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Use Cases ── */}
      <section className="py-24">
        <div className="container">
          <div className="text-center mb-14">
            <h2 className="text-3xl sm:text-4xl font-bold mb-4" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
              Built for Real-World Protection
            </h2>
            <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
              From personal anti-scam protection to enterprise content moderation — DeepGuard covers every use case.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {useCases.map((u, i) => (
              <Link key={i} href={u.href}>
                <div className="group p-5 rounded-xl border border-border/60 bg-card hover:border-primary/40 transition-all duration-300 cursor-pointer h-full">
                  <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center mb-4 group-hover:bg-primary/20 transition-colors">
                    <u.icon className="w-5 h-5 text-primary" />
                  </div>
                  <h3 className="font-semibold text-foreground mb-2 text-sm">{u.title}</h3>
                  <p className="text-xs text-muted-foreground leading-relaxed">{u.desc}</p>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* ── Training Data & Credibility ── */}
      <section className="py-20 bg-card/30 border-y border-border/40">
        <div className="container">
          <div className="max-w-4xl mx-auto">
            <div className="text-center mb-10">
              <h2 className="text-2xl sm:text-3xl font-bold mb-3" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
                Trained on Industry Benchmark Datasets
              </h2>
              <p className="text-muted-foreground">Our models are validated against the same datasets used by leading academic research.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
              {[
                { name: 'FaceForensics++', desc: '1M+ manipulated video frames covering FaceSwap, NeuralTextures, Face2Face', tag: 'Video Deepfake' },
                { name: 'DFDC (DeepFake Detection Challenge)', desc: 'Facebook AI Research dataset with 100K+ video clips across diverse demographics', tag: 'Video Deepfake' },
                { name: 'LAION-5B', desc: 'Large-scale image dataset used to train and evaluate diffusion model detectors', tag: 'AI Image' },
              ].map((d, i) => (
                <div key={i} className="p-5 rounded-xl border border-border/60 bg-card">
                  <div className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-primary/10 border border-primary/20 mb-3">
                    <Database className="w-3 h-3 text-primary" />
                    <span className="text-[10px] text-primary font-medium">{d.tag}</span>
                  </div>
                  <h4 className="font-semibold text-foreground text-sm mb-2">{d.name}</h4>
                  <p className="text-xs text-muted-foreground leading-relaxed">{d.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── Trust indicators ── */}
      <section className="py-16">
        <div className="container">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-3xl mx-auto">
            {[
              { icon: Lock, title: 'Privacy First', desc: 'Files are deleted immediately after analysis. We never store your content.' },
              { icon: Zap, title: 'Fast Analysis', desc: 'Average 5 seconds per file. Real-time protection without the wait.' },
              { icon: Globe2, title: 'Global Coverage', desc: '13 languages supported. Designed for users worldwide.' },
            ].map((item, i) => (
              <div key={i} className="flex items-start gap-4 p-5 rounded-xl border border-border/40 bg-card/40">
                <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                  <item.icon className="w-4 h-4 text-primary" />
                </div>
                <div>
                  <h4 className="font-medium text-foreground mb-1">{item.title}</h4>
                  <p className="text-xs text-muted-foreground leading-relaxed">{item.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA ── */}
      <section className="py-24 relative overflow-hidden">
        <div className="absolute inset-0 bg-primary/5 grid-bg" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[400px] h-[400px] bg-primary/10 rounded-full blur-[100px]" />
        <div className="container relative z-10 text-center">
          <div className="inline-flex items-center gap-2 mb-4">
            <CheckCircle2 className="w-5 h-5 text-primary" />
            <span className="text-primary font-medium">Free to start — no credit card required</span>
          </div>
          <h2 className="text-3xl sm:text-4xl font-bold mb-4" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
            Start detecting AI content now
          </h2>
          <p className="text-muted-foreground text-lg mb-8 max-w-xl mx-auto">
            Upload any image, video, audio file, or paste text. Get a detailed authenticity report in seconds.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/detect/text">
              <Button size="lg" className="bg-primary text-primary-foreground hover:bg-primary/90 glow-cyan gap-2 px-10 text-base">
                Detect Text
                <ArrowRight className="w-4 h-4" />
              </Button>
            </Link>
            <Link href="/detect/video">
              <Button size="lg" variant="outline" className="border-border hover:border-primary/50 gap-2 px-10 text-base">
                Detect Image / Video
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer className="border-t border-border/40 py-10">
        <div className="container">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <Shield className="w-5 h-5 text-primary" />
              <span className="font-bold text-foreground" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
                Deep<span className="text-primary">Guard</span>
              </span>
            </div>
            <p className="text-sm text-muted-foreground text-center">AI Deepfake Detection & Anti-Scam Platform</p>
            <p className="text-xs text-muted-foreground">© 2025 DeepGuard. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
