import { useEffect } from 'react';
import { FileText } from 'lucide-react';

export default function Terms() {
  useEffect(() => { document.title = 'Terms of Service — DeepGuard'; }, []);

  return (
    <div className="min-h-screen">
      <section className="pt-24 pb-16">
        <div className="container max-w-3xl">
          <div className="flex items-center gap-3 mb-8">
            <FileText className="w-8 h-8 text-primary" />
            <h1 className="text-3xl sm:text-4xl font-bold" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>Terms of Service</h1>
          </div>
          <p className="text-sm text-muted-foreground mb-8">Last updated: April 2026</p>

          <div className="prose prose-invert prose-sm max-w-none space-y-8">
            <div>
              <h2 className="text-xl font-bold text-foreground mb-3" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>1. Service Description</h2>
              <p className="text-muted-foreground leading-relaxed">DeepGuard provides AI-powered deepfake detection services for images, video, audio, and text content. Our platform uses multiple detection engines to analyze uploaded content and provide probability assessments of whether content is AI-generated or manipulated.</p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-foreground mb-3" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>2. Accuracy Disclaimer</h2>
              <p className="text-muted-foreground leading-relaxed">DeepGuard's detection results are probabilistic assessments, not definitive determinations. While we strive for high accuracy, no detection system is 100% reliable. Results should be used as one factor in your assessment and should not be the sole basis for legal, financial, or consequential decisions. For legal proceedings, we recommend combining DeepGuard analysis with expert human review.</p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-foreground mb-3" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>3. Acceptable Use</h2>
              <p className="text-muted-foreground leading-relaxed">You may use DeepGuard for legitimate purposes including: verifying media authenticity, protecting against fraud, journalistic fact-checking, academic research, and personal safety. You may not use DeepGuard to: harass or stalk individuals, circumvent content moderation systems, generate training data for creating deepfakes, or any illegal purpose.</p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-foreground mb-3" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>4. Usage Limits</h2>
              <p className="text-muted-foreground leading-relaxed">Free accounts are limited to 10 detections per month. Paid plans have limits as specified on our pricing page. Abuse of the service (automated scraping, excessive requests, attempting to bypass limits) may result in account suspension.</p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-foreground mb-3" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>5. Intellectual Property</h2>
              <p className="text-muted-foreground leading-relaxed">You retain all rights to content you upload. We do not claim ownership of your files. Detection results and reports generated by DeepGuard may be shared, published, or used in legal proceedings. The DeepGuard platform, branding, and technology are proprietary.</p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-foreground mb-3" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>6. Limitation of Liability</h2>
              <p className="text-muted-foreground leading-relaxed">DeepGuard is provided "as is" without warranties of any kind. We are not liable for damages arising from reliance on detection results, service interruptions, or data loss. Our total liability is limited to the amount you paid for the service in the preceding 12 months.</p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-foreground mb-3" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>7. Changes to Terms</h2>
              <p className="text-muted-foreground leading-relaxed">We may update these terms from time to time. Continued use of the service after changes constitutes acceptance. Material changes will be communicated via email or platform notification.</p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-foreground mb-3" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>8. Contact</h2>
              <p className="text-muted-foreground leading-relaxed">For questions about these terms: <a href="mailto:legal@deepguard.org" className="text-primary hover:underline">legal@deepguard.org</a></p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
